name: ease_http
description:
  Based on Dart http package, makes http package more powerful and easier to
  use.
version: 0.1.8
homepage: https://github.com/hanlogy/ease_http

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  http: ^1.2.1
  http_parser: ^4.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
