name: ease_http
description: Based on Dart http package, makes http package more powerful and easier to use.
version: 0.1.6
homepage: https://github.com/hanlogy/ease_http

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.0.0
  http_parser: ^4.0.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
