name: ease_http
description: Based on Dart http package, makes http package more powerful and easier to use.
version: 0.1.4
homepage: https://github.com/hanlogy/ease_http

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
